package com.nirikshan.model;

public enum RecommendationType {
    REDIRECT, DEPLOY_SECURITY, OPEN_ROUTE, CLOSE_ENTRY, ANNOUNCEMENT, REASSIGN_PERSONNEL,
    ONE_WAY_FLOW, OPEN_BARRICADE_GAP, CLOSE_BARRICADE_GAP, NARROW_ENTRY,
    CREATE_ONE_WAY_CHANNEL, REMOVE_CROSSFLOW, GATE_ACTION
}
