"""Replay pre-generated Nirikshan events to the Spring Boot ingestion API."""

from __future__ import annotations

import argparse
import json
import time
from datetime import datetime
from pathlib import Path
from typing import Any

import requests


def parse_timestamp(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def post_with_retry(event: dict[str, Any], url: str, timeout: float) -> bool:
    for attempt in (1, 2):
        try:
            response = requests.post(url, json=event, timeout=timeout)
            print(f"POST attempt {attempt}: HTTP {response.status_code} | zone={event['zoneId']} | level={event['riskLevel']} | timestamp={event['timestamp']}")
            if response.ok:
                return True
            if attempt == 1:
                print("  Response was not successful; retrying once...")
        except requests.RequestException as error:
            print(f"POST attempt {attempt}: connection error: {error}")
            if attempt == 1:
                print("  Retrying once...")
    print(f"  Skipped event after retry: zone={event['zoneId']} timestamp={event['timestamp']}")
    return False


def replay(events: list[dict[str, Any]], url: str, speed: float, timeout: float) -> tuple[int, int]:
    ordered = sorted(events, key=lambda event: parse_timestamp(event["timestamp"]))
    successful = 0
    skipped = 0
    previous_time: datetime | None = None
    for index, event in enumerate(ordered, start=1):
        event_time = parse_timestamp(event["timestamp"])
        if previous_time is not None:
            delay = max(0.0, (event_time - previous_time).total_seconds()) / speed
            if delay:
                print(f"Waiting {delay:.2f}s before event {index}/{len(ordered)}...")
                time.sleep(delay)
        print(f"Replaying event {index}/{len(ordered)}")
        if post_with_retry(event, url, timeout):
            successful += 1
        else:
            skipped += 1
        previous_time = event_time
    return successful, skipped


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Replay Nirikshan events with original timestamp spacing")
    parser.add_argument("--events", required=True, help="events.json generated by process_video.py")
    parser.add_argument("--url", default="http://localhost:8080/api/risk-events", help="Backend ingestion URL")
    parser.add_argument("--speed", type=float, default=1.0, help="Replay speed multiplier; 2.0 is twice as fast")
    parser.add_argument("--timeout", type=float, default=10.0, help="HTTP request timeout in seconds")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.speed <= 0:
        raise SystemExit("--speed must be greater than zero")
    events = json.loads(Path(args.events).read_text(encoding="utf-8"))
    if not isinstance(events, list):
        raise SystemExit("events JSON must contain an array")
    successful, skipped = replay(events, args.url, args.speed, args.timeout)
    print(f"Replay complete: {successful} posted, {skipped} skipped")


if __name__ == "__main__":
    main()
