"use client";

import { FormEvent, useEffect, useState } from "react";
import AppShell, { NavItem, primaryNavItems, type PreviewRole } from "../../components/AppShell";
import Icon from "../../components/Icon";
import { Button, Card, Field, Input, Spinner } from "../../components/ui";
import { api, clearSession, readSession, saveSession, type Session, type UserInfo } from "../../lib/auth";
import styles from "./security.module.css";

const navItems: NavItem[] = [{ label: "Safety alerts", href: "/alerts", icon: "bell" }, { label: "Report issue", href: "/alerts/report", icon: "activity" }, { label: "Account", href: "/alerts/security", icon: "settings" }];
const securityNavItems: NavItem[] = [{ label: "Assigned zone", href: "/security", icon: "grid" }, { label: "Citizen reports", href: "/security/reports", icon: "activity" }, { label: "Instructions", href: "/security#instructions", icon: "activity" }, { label: "Security", href: "/alerts/security", icon: "lock" }];
type Step = "verify" | "content";
type Panel = "account" | "create" | "admins";
type CreatedAdmin = { user: UserInfo; temporaryPassword: string };

function Verify({ session, onVerified }: { session: Session; onVerified: (verified: Session) => void }) {
  const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [working, setWorking] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setWorking(true); setError(""); try { const verified = await api<Session>("/api/auth/login", { method: "POST", body: JSON.stringify({ email: session.user.email, password }) }); saveSession(verified); onVerified(verified); } catch (reason) { setError(reason instanceof Error ? reason.message : "Current password could not be verified"); } finally { setWorking(false); } }
  return <div className={styles.verifyLayout}><div className={styles.verifyIntro}><span className={styles.lockBadge}>LOCKED</span><span className={styles.kicker}>STEP UP AUTHENTICATION</span><h2>Verify your identity</h2><p>Security settings require a fresh password check, even when you are already signed in.</p></div><form className={styles.verifyForm} onSubmit={submit}><Field label="Current password"><Input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" required autoFocus /></Field>{error && <div className={styles.error} role="alert">{error}</div>}<Button size="lg" disabled={working}>{working ? "Checking password" : "Continue to security settings"}</Button><p className={styles.note}>Signed in as {session.user.email}</p></form></div>;
}

function PasswordPanel({ session, onUpdated, onClose }: { session: Session; onUpdated: (user: UserInfo) => void; onClose: () => void }) {
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [working, setWorking] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setNotice(""); if (newPassword !== confirmPassword) { setError("New passwords do not match."); return; } setWorking(true); try { const user = await api<UserInfo>("/api/auth/change-password", { method: "POST", body: JSON.stringify({ currentPassword, newPassword }) }); onUpdated(user); setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); setNotice("Your password has been updated."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not change password"); } finally { setWorking(false); } }
  return <div className={styles.modalBackdrop}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="password-dialog-title"><div className={styles.modalHeader}><div><span className={styles.kicker}>YOUR ACCOUNT</span><h2 id="password-dialog-title">Change your own password</h2><p>Use a strong password that is unique to this account.</p></div><button className={styles.closeButton} type="button" onClick={onClose} aria-label="Close password form"><Icon name="close" /></button></div><form onSubmit={submit}><Field label="Current password"><Input type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} autoComplete="current-password" required autoFocus /></Field><Field label="New password" hint="At least 8 characters"><Input type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} autoComplete="new-password" minLength={8} required /></Field><Field label="Confirm new password"><Input type="password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} autoComplete="new-password" minLength={8} required /></Field>{error && <div className={styles.error} role="alert">{error}</div>}{notice && <div className={styles.notice} role="status">{notice}</div>}<div className={styles.modalActions}><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button disabled={working}>{working ? "Updating password" : "Update password"}</Button></div></form></section></div>;
}

function CreateAdminPanel({ onCancel }: { onCancel: () => void }) {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [temporaryPassword, setTemporaryPassword] = useState(""); const [error, setError] = useState(""); const [working, setWorking] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setWorking(true); setError(""); setTemporaryPassword(""); try { const result = await api<CreatedAdmin>("/api/admin/users", { method: "POST", body: JSON.stringify({ name, email, role: "ADMIN", assignedZoneId: null }) }); setTemporaryPassword(result.temporaryPassword); setName(""); setEmail(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not create administrator"); } finally { setWorking(false); } }
  return <Card className={styles.formCard}><div className={styles.modalHeader}><div><span className={styles.kicker}>ADMINISTRATOR ACCESS</span><h2>Create admin</h2><p>Create an administrator account with a temporary password. They will be asked to set a new password when they first sign in.</p></div><button className={styles.closeButton} type="button" onClick={onCancel} aria-label="Close create admin form"><Icon name="close" /></button></div><form onSubmit={submit}><Field label="Full name"><Input value={name} onChange={(event) => setName(event.target.value)} autoComplete="name" placeholder="Full name" required /></Field><Field label="Email"><Input value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" type="email" placeholder="admin@example.com" required /></Field>{error && <div className={styles.error} role="alert">{error}</div>}{temporaryPassword && <div className={styles.temporaryPassword} role="status"><strong>Temporary password</strong><span>{temporaryPassword}</span><small>Copy this now. It will not be shown again.</small></div>}<div className={styles.modalActions}><Button type="button" variant="ghost" onClick={onCancel}>Cancel</Button><Button disabled={working}>{working ? "Creating administrator" : "Create administrator"}</Button></div></form></Card>;
}

function AdminDirectory() {
  const [admins, setAdmins] = useState<UserInfo[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [editingId, setEditingId] = useState<number>(); const [name, setName] = useState(""); const [newPassword, setNewPassword] = useState(""); const [working, setWorking] = useState(false);
  async function load() { setLoading(true); setError(""); try { setAdmins(await api<UserInfo[]>("/api/admin/admins")); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load administrators"); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  function startEdit(admin: UserInfo) { setEditingId(admin.id); setName(admin.name); setNewPassword(""); setNotice(""); }
  async function save(event: FormEvent) { event.preventDefault(); if (!editingId) return; setWorking(true); setError(""); setNotice(""); try { const updated = await api<UserInfo>(`/api/admin/admins/${editingId}`, { method: "PATCH", body: JSON.stringify({ name, newPassword: newPassword || null }) }); setAdmins((current) => current.map((admin) => admin.id === updated.id ? updated : admin)); setEditingId(undefined); setNotice("Administrator details updated."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not update administrator"); } finally { setWorking(false); } }
  async function remove(admin: UserInfo) { if (!window.confirm(`Delete ${admin.name} from the database?`)) return; setError(""); setNotice(""); try { await api<void>(`/api/admin/admins/${admin.id}`, { method: "DELETE" }); setAdmins((current) => current.filter((item) => item.id !== admin.id)); setNotice("Administrator deleted."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not delete administrator"); } }
  return <Card className={styles.adminsCard}><div className={styles.cardHeader}><span className={styles.kicker}>ADMINISTRATOR DIRECTORY</span><h2>Current admins</h2><p>Only the main administrator can change or delete other administrator accounts.</p></div>{error && <div className={styles.error} role="alert">{error}</div>}{notice && <div className={styles.notice} role="status">{notice}</div>}{loading ? <Spinner label="Loading administrators" /> : <div className={styles.adminList}>{admins.map((admin) => <article className={styles.adminRow} key={admin.id}><div className={styles.adminIdentity}><strong>{admin.name}</strong><span>{admin.email}</span><small>{admin.protectedAdmin ? "Main administrator" : "Administrator"}</small></div>{admin.protectedAdmin ? <span className={styles.protectedLabel}>Protected</span> : editingId === admin.id ? <form className={styles.adminEdit} onSubmit={save}><Field label="Name"><Input value={name} onChange={(event) => setName(event.target.value)} required /></Field><Field label="New password" hint="Leave blank to keep the current password"><Input type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} minLength={8} autoComplete="new-password" /></Field><div className={styles.adminEditActions}><Button size="sm" disabled={working}>{working ? "Saving" : "Save changes"}</Button><Button type="button" variant="ghost" size="sm" onClick={() => setEditingId(undefined)}>Cancel</Button></div></form> : <div className={styles.adminActions}><Button variant="secondary" size="sm" onClick={() => startEdit(admin)}>Edit admin</Button><Button variant="danger" size="sm" onClick={() => remove(admin)}>Delete</Button></div>}</article>)}</div>}</Card>;
}

function ProfileCard({ session }: { session: Session }) { return <Card className={styles.profileCard}><span className={styles.kicker}>ACCOUNT</span><h2>{session.user.name}</h2><p>{session.user.email}</p><div className={styles.profileMeta}><span>Role</span><strong>{session.user.role === "ADMIN" ? "Administrator" : session.user.role === "SECURITY" ? "Security operator" : "Campus member"}</strong></div><div className={styles.profileMeta}><span>Access</span><strong>{session.user.active ? "Active" : "Inactive"}</strong></div><div className={styles.profileMeta}><span>Security check</span><strong>Verified for this session</strong></div></Card>; }

function SecurityContent({ session, onUpdated }: { session: Session; onUpdated: (user: UserInfo) => void }) {
  const isAdmin = session.user.role === "ADMIN"; const [canManageAdmins, setCanManageAdmins] = useState(Boolean(session.user.protectedAdmin)); const [permissionLoading, setPermissionLoading] = useState(isAdmin); const [panel, setPanel] = useState<Panel>(session.user.protectedAdmin ? "admins" : "account"); const [passwordOpen, setPasswordOpen] = useState(false);
  useEffect(() => { if (!isAdmin) { setPermissionLoading(false); return; } api<UserInfo[]>("/api/admin/admins").then(() => setCanManageAdmins(true)).catch(() => setCanManageAdmins(false)).finally(() => setPermissionLoading(false)); }, [isAdmin]);
  return <div className={styles.securityWorkspace}><Card className={styles.actionCard}><div><span className={styles.kicker}>SECURITY CONTROLS</span><h2>Choose an account action</h2><p>{isAdmin && canManageAdmins ? "Manage your own credentials or administer the other admin accounts." : isAdmin ? "You can change your own password. Administrator accounts are managed by the main administrator." : "Manage your own account credentials."}</p></div><div className={styles.actionButtons}>{isAdmin && <Button variant={panel === "create" ? "primary" : "secondary"} onClick={() => setPanel("create")} disabled={permissionLoading || !canManageAdmins}>Create admin</Button>}<Button variant="primary" onClick={() => setPasswordOpen(true)}>Change your own password</Button></div></Card>{isAdmin && canManageAdmins && <div className={styles.securityTabs} role="tablist" aria-label="Security settings sections"><button type="button" role="tab" aria-selected={panel === "account" || panel === "create"} className={panel === "admins" ? "" : styles.selectedTab} onClick={() => setPanel("account")}>Your account</button><button type="button" role="tab" aria-selected={panel === "admins"} className={panel === "admins" ? styles.selectedTab : ""} onClick={() => setPanel("admins")}>Administrators</button></div>}{panel === "admins" && canManageAdmins ? <AdminDirectory /> : panel === "create" && canManageAdmins ? <CreateAdminPanel onCancel={() => setPanel("admins")} /> : <ProfileCard session={session} />}{passwordOpen && <PasswordPanel session={session} onUpdated={onUpdated} onClose={() => setPasswordOpen(false)} />}</div>;
}

function SecurityPage({ session }: { session: Session }) { const previewParam = typeof window === "undefined" ? null : new URLSearchParams(window.location.search).get("preview"); const previewRole: PreviewRole | undefined = session.user.role === "ADMIN" && previewParam === "security" ? "SECURITY" : session.user.role === "ADMIN" && previewParam === "customer" ? "CITIZEN" : undefined; const previewSession = previewRole ? { ...session, user: { ...session.user, role: previewRole, assignedZoneName: previewRole === "SECURITY" ? session.user.assignedZoneName || "Test security zone" : null, mustChangePassword: false } } : session; const [step, setStep] = useState<Step>(previewRole ? "content" : "verify"); const [currentSession, setCurrentSession] = useState(previewSession); const complete = (user: UserInfo) => { const next = { ...currentSession, user }; saveSession(next); setCurrentSession(next); }; const verified = (next: Session) => { saveSession(next); setCurrentSession(next); setStep("content"); }; const isAdmin = currentSession.user.role === "ADMIN"; const items = previewRole === "SECURITY" ? securityNavItems : previewRole === "CITIZEN" ? navItems : isAdmin ? primaryNavItems : navItems; return <AppShell user={session.user} previewRole={previewRole} title="Security settings" subtitle={previewRole ? "Previewing account access for this workspace" : "Sensitive account actions are protected by step up verification"} active={previewRole ? "Account" : isAdmin ? "Security" : "Account"} navItems={items}>{previewRole ? <ProfileCard session={currentSession} /> : step === "verify" ? <Verify session={currentSession} onVerified={verified} /> : <SecurityContent session={currentSession} onUpdated={complete} />}</AppShell>; }

export default function Page() { const [session, setSession] = useState<Session>(); useEffect(() => { const next = readSession(); if (!next) { clearSession(); window.location.replace("/alerts"); return; } setSession(next); }, []); if (!session) return <main className={styles.state}>Checking security access</main>; return <SecurityPage session={session} />; }
