"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, type Role, type UserInfo } from "../lib/auth";
import styles from "./console.module.css";

type Zone = { id: number; name: string };
type Created = { user: UserInfo; temporaryPassword: string };

export default function AdminManagement({ zones }: { zones: Zone[] }) {
  const [users, setUsers] = useState<UserInfo[]>([]); const [name, setName] = useState(""); const [email, setEmail] = useState("");
  const [role, setRole] = useState<Role>("SECURITY"); const [zoneId, setZoneId] = useState(""); const [temp, setTemp] = useState(""); const [message, setMessage] = useState(""); const [target, setTarget] = useState("all"); const [status, setStatus] = useState("");
  const securityUsers = useMemo(() => users.filter((u) => u.role === "SECURITY" && u.active), [users]);
  const load = async () => { try { setUsers(await api<UserInfo[]>("/api/admin/users")); } catch (err) { setStatus(err instanceof Error ? err.message : "Could not load users"); } };
  useEffect(() => { load(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setStatus(""); setTemp(""); try { const result = await api<Created>("/api/admin/users", { method: "POST", body: JSON.stringify({ name, email, role, assignedZoneId: role === "SECURITY" ? Number(zoneId) : null }) }); setTemp(result.temporaryPassword); setName(""); setEmail(""); setZoneId(""); await load(); } catch (err) { setStatus(err instanceof Error ? err.message : "Could not create account"); } }
  async function deactivate(id: number) { if (!window.confirm("Deactivate this account?")) return; try { await api<void>(`/api/admin/users/${id}`, { method: "DELETE" }); await load(); } catch (err) { setStatus(err instanceof Error ? err.message : "Could not deactivate account"); } }
  async function send(event: FormEvent) { event.preventDefault(); setStatus(""); try { const body = target === "all" ? { message } : target.startsWith("zone:") ? { message, targetZoneId: Number(target.slice(5)) } : { message, targetSecurityUserId: Number(target.slice(5)) }; await api("/api/admin/instructions", { method: "POST", body: JSON.stringify(body) }); setMessage(""); setStatus("Instruction sent."); } catch (err) { setStatus(err instanceof Error ? err.message : "Could not send instruction"); } }
  return <section className={styles.management}><div><span className={styles.eyebrow}>ACCESS & COORDINATION</span><h2>Security personnel</h2></div><div className={styles.managementGrid}><form onSubmit={create} className={styles.managementCard}><h3>Create account</h3><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Full name" required /><input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email address" type="email" required /><select value={role} onChange={(e) => setRole(e.target.value as Role)}><option value="SECURITY">Security personnel</option><option value="ADMIN">Administrator</option></select>{role === "SECURITY" && <select value={zoneId} onChange={(e) => setZoneId(e.target.value)} required><option value="">Assign a zone…</option>{zones.map((z) => <option value={z.id} key={z.id}>{z.name}</option>)}</select>}<button>Create temporary account</button>{temp && <p className={styles.tempPassword}>Temporary password — copy once: <b>{temp}</b></p>}</form><div className={styles.managementCard}><h3>Active personnel</h3>{securityUsers.length ? securityUsers.map((u) => <div className={styles.person} key={u.id}><span><b>{u.name}</b><small>{u.email} · {u.assignedZoneName || "No zone"}</small></span><button onClick={() => deactivate(u.id)}>Deactivate</button></div>) : <p>No security accounts created yet.</p>}</div><form onSubmit={send} className={styles.managementCard}><h3>Send instruction</h3><select value={target} onChange={(e) => setTarget(e.target.value)}><option value="all">All security personnel</option>{zones.map((z) => <option value={`zone:${z.id}`} key={`z${z.id}`}>{z.name} team</option>)}{securityUsers.map((u) => <option value={`user:${u.id}`} key={`u${u.id}`}>{u.name}</option>)}</select><textarea value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Clear, actionable instruction…" required maxLength={2000} /><button>Send instruction</button></form></div>{status && <p className={styles.managementStatus}>{status}</p>}</section>;
}
