"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Button, Field, Input, Select, Textarea } from "../components/ui";
import { api, type UserInfo } from "../lib/auth";
import styles from "./management.module.css";

type Zone = { id: number; name: string };
type Created = { user: UserInfo; temporaryPassword: string };

export default function AdminManagement({ zones, view = "overview" }: { zones: Zone[]; view?: "overview" | "staff" }) {
  const [users, setUsers] = useState<UserInfo[]>([]); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [zoneId, setZoneId] = useState(""); const [temp, setTemp] = useState(""); const [message, setMessage] = useState(""); const [target, setTarget] = useState("all"); const [status, setStatus] = useState("");
  const securityUsers = useMemo(() => users.filter((user) => user.role === "SECURITY" && user.active), [users]);
  const load = async () => { try { setUsers(await api<UserInfo[]>("/api/admin/users")); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Could not load users"); } };
  useEffect(() => { load(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setStatus(""); setTemp(""); try { const result = await api<Created>("/api/admin/users", { method: "POST", body: JSON.stringify({ name, email, role: "SECURITY", assignedZoneId: Number(zoneId) }) }); setTemp(result.temporaryPassword); setName(""); setEmail(""); setZoneId(""); await load(); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Could not create account"); } }
  async function deactivate(id: number) { if (!window.confirm("Deactivate this account?")) return; try { await api<void>(`/api/admin/users/${id}`, { method: "DELETE" }); await load(); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Could not deactivate account"); } }
  async function send(event: FormEvent) { event.preventDefault(); setStatus(""); try { const body = target === "all" ? { message } : target.startsWith("zone:") ? { message, targetZoneId: Number(target.slice(5)) } : { message, targetSecurityUserId: Number(target.slice(5)) }; await api("/api/admin/instructions", { method: "POST", body: JSON.stringify(body) }); setMessage(""); setStatus("Instruction sent."); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Could not send instruction"); } }
  const staffCard = <form onSubmit={create} className={styles.managementCard}><span className={styles.cardKicker}>STAFF ACCESS</span><h3>Create a security account</h3><Field label="Full name"><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="Full name" required /></Field><Field label="Email"><Input value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email address" type="email" required /></Field><Field label="Assigned zone"><Select value={zoneId} onChange={(event) => setZoneId(event.target.value)} required><option value="">Choose a zone</option>{zones.map((zone) => <option value={zone.id} key={zone.id}>{zone.name}</option>)}</Select></Field><Button type="submit">Create temporary account</Button>{temp && <p className={styles.temp}>Temporary password, copy once: <b>{temp}</b></p>}</form>;
  const activeStaffCard = <section className={styles.managementCard}><span className={styles.cardKicker}>ACTIVE STAFF</span><h3>Security personnel</h3>{securityUsers.length ? <div className={styles.people}>{securityUsers.map((user) => <div className={styles.person} key={user.id}><div><strong>{user.name}</strong><small>{user.email}</small><small>{user.assignedZoneName || "No zone assigned"}</small></div><Button variant="danger" size="sm" type="button" onClick={() => deactivate(user.id)}>Deactivate</Button></div>)}</div> : <p className={styles.empty}>No security accounts created yet.</p>}</section>;
  const commandNotesCard = <form onSubmit={send} className={styles.managementCard}><span className={styles.cardKicker}>COMMAND NOTES</span><h3>Send an instruction</h3><Field label="Audience"><Select value={target} onChange={(event) => setTarget(event.target.value)}><option value="all">All security personnel</option>{zones.map((zone) => <option value={`zone:${zone.id}`} key={`z${zone.id}`}>{zone.name} team</option>)}{securityUsers.map((user) => <option value={`user:${user.id}`} key={`u${user.id}`}>{user.name}</option>)}</Select></Field><Field label="Message"><Textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Enter a clear instruction" required maxLength={2000} /></Field><Button type="submit">Send instruction</Button></form>;
  return <div className={styles.management}><section className={styles.managementHeader}><div><span className={styles.kicker}>{view === "staff" ? "STAFF ACCESS" : "ACCESS AND COORDINATION"}</span><h2>{view === "staff" ? "Staff access" : "Administration workspace"}</h2><p>{view === "staff" ? "Create and manage staff accounts for the operations team." : "Manage operational access and coordinate response from one place."}</p></div><span className={styles.scope}>Admin only</span></section><div className={`${styles.managementGrid} ${view === "staff" ? styles.staffOnly : ""}`}>{view === "staff" ? staffCard : <>{activeStaffCard}{commandNotesCard}</>}</div>{status && <p className={styles.status} role="status">{status}</p>}</div>;
}
