"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Button, Field, Input, Select, Textarea } from "../components/ui";
import { api, type UserInfo } from "../lib/auth";
import styles from "./management.module.css";

type Zone = { id: number; name: string };
type Created = { user: UserInfo; temporaryPassword: string };

export default function AdminManagement({ zones, view = "overview" }: { zones: Zone[]; view?: "overview" | "staff" | "directory" | "messages" }) {
  const [users, setUsers] = useState<UserInfo[]>([]); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [zoneId, setZoneId] = useState(""); const [temp, setTemp] = useState(""); const [message, setMessage] = useState(""); const [target, setTarget] = useState("all"); const [status, setStatus] = useState("");
  const [passwordUserId, setPasswordUserId] = useState<number>(); const [newPassword, setNewPassword] = useState(""); const [passwordWorking, setPasswordWorking] = useState(false);
  const [actionContext, setActionContext] = useState<{ recommendationId?: number; alertId?: number }>({});
  const securityUsers = useMemo(() => users.filter((user) => user.role === "SECURITY" && user.active), [users]);
  const load = async () => { try { setUsers(await api<UserInfo[]>("/api/admin/users")); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Could not load users"); } };
  useEffect(() => { load(); }, []);
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const contextZoneId = params.get("zoneId");
    const recommendationId = params.get("recommendationId");
    const alertId = params.get("alertId");
    if (contextZoneId) setTarget(`zone:${contextZoneId}`);
    if (params.get("message")) setMessage(params.get("message") || "");
    setActionContext({
      ...(recommendationId ? { recommendationId: Number(recommendationId) } : {}),
      ...(alertId ? { alertId: Number(alertId) } : {}),
    });
    if (recommendationId || alertId) setStatus("Review the pre-filled instruction, then send it to complete the response.");
  }, []);
  async function create(event: FormEvent) { event.preventDefault(); setStatus(""); setTemp(""); try { const result = await api<Created>("/api/admin/users", { method: "POST", body: JSON.stringify({ name, email, role: "SECURITY", assignedZoneId: Number(zoneId) }) }); setTemp(result.temporaryPassword); setName(""); setEmail(""); setZoneId(""); await load(); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Could not create account"); } }
  async function deactivate(id: number) { if (!window.confirm("Deactivate this account?")) return; try { await api<void>(`/api/admin/users/${id}`, { method: "DELETE" }); await load(); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Could not deactivate account"); } }
  async function changePassword(event: FormEvent, id: number) { event.preventDefault(); if (newPassword.length < 8) { setStatus("Password must be at least 8 characters"); return; } setPasswordWorking(true); setStatus(""); try { await api<UserInfo>(`/api/admin/users/${id}/password`, { method: "PATCH", body: JSON.stringify({ newPassword }) }); setPasswordUserId(undefined); setNewPassword(""); setStatus("Password changed successfully"); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Could not change password"); } finally { setPasswordWorking(false); } }
  async function send(event: FormEvent) { event.preventDefault(); setStatus(""); try { const base = target === "all" ? { message } : target.startsWith("zone:") ? { message, targetZoneId: Number(target.slice(5)) } : { message, targetSecurityUserId: Number(target.slice(5)) }; const body = { ...base, ...actionContext }; await api("/api/admin/instructions", { method: "POST", body: JSON.stringify(body) }); setMessage(""); setActionContext({}); setStatus("Instruction sent. The originating item is now acknowledged/resolved."); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Could not send instruction"); } }
  const staffCard = <form onSubmit={create} className={styles.managementCard}><span className={styles.cardKicker}>STAFF ACCESS</span><h3>Create a security account</h3><Field label="Full name"><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="Full name" required /></Field><Field label="Email"><Input value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email address" type="email" required /></Field><Field label="Assigned zone"><Select value={zoneId} onChange={(event) => setZoneId(event.target.value)} required><option value="">Choose a zone</option>{zones.map((zone) => <option value={zone.id} key={zone.id}>{zone.name}</option>)}</Select></Field><Button type="submit">Create temporary account</Button>{temp && <div className={styles.temp}><span>Temporary password, copy once: <b>{temp}</b></span><Button type="button" variant="secondary" size="sm" onClick={() => setTemp("")}>Done</Button></div>}</form>;
  const activeStaffCard = <section className={styles.managementCard}><span className={styles.cardKicker}>STAFF DIRECTORY</span><h3>Security personnel</h3>{securityUsers.length ? <div className={styles.staffTableWrap}><table className={styles.staffTable}><thead><tr><th>Name</th><th>Email</th><th>Assigned zone</th><th>Actions</th></tr></thead><tbody>{securityUsers.map((user) => <tr key={user.id}><td>{user.name}</td><td>{user.email}</td><td>{user.assignedZoneName || "No zone assigned"}</td><td><div className={styles.staffActions}><Button variant="danger" size="sm" type="button" onClick={() => deactivate(user.id)}>Deactivate</Button><Button variant="secondary" size="sm" type="button" onClick={() => { setPasswordUserId(user.id); setNewPassword(""); }}>Change password</Button></div></td></tr>)}</tbody></table></div> : <p className={styles.empty}>No security accounts created yet.</p>}</section>;
  const commandNotesCard = <form onSubmit={send} className={styles.managementCard}><span className={styles.cardKicker}>COMMAND NOTES</span><h3>Send an instruction</h3><Field label="Audience"><Select value={target} onChange={(event) => setTarget(event.target.value)}><option value="all">All security personnel</option>{zones.map((zone) => <option value={`zone:${zone.id}`} key={`z${zone.id}`}>{zone.name} team</option>)}{securityUsers.map((user) => <option value={`user:${user.id}`} key={`u${user.id}`}>{user.name}</option>)}</Select></Field><Field label="Message"><Textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Enter a clear instruction" required maxLength={2000} /></Field><Button type="submit">Send instruction</Button></form>;
  const heading = view === "staff" ? "Staff access" : view === "messages" ? "Send instructions" : "Administration workspace";
  const description = view === "staff" ? "Create security accounts and review the complete staff list." : view === "messages" ? "Send a clear instruction to all security personnel, a zone team, or one person." : "Manage operational access and coordinate response from one place.";
  const selectedPasswordUser = securityUsers.find((user) => user.id === passwordUserId);
  return <div className={styles.management}><section className={styles.managementHeader}><div><span className={styles.kicker}>{view === "staff" ? "STAFF ACCESS" : view === "messages" ? "COMMAND NOTES" : "ACCESS AND COORDINATION"}</span><h2>{heading}</h2><p>{description}</p></div><span className={styles.scope}>Admin only</span></section><div className={`${styles.managementGrid} ${view === "staff" ? styles.staffOnly : ""}`}>{view === "staff" ? <>{staffCard}{activeStaffCard}</> : view === "directory" ? activeStaffCard : view === "messages" ? commandNotesCard : <>{activeStaffCard}{commandNotesCard}</>}</div>{status && <p className={styles.status} role="status">{status}</p>}{selectedPasswordUser && <div className={styles.modalBackdrop} role="presentation"><section className={styles.passwordModal} role="dialog" aria-modal="true" aria-labelledby="password-modal-title"><span className={styles.cardKicker}>ACCOUNT SECURITY</span><h3 id="password-modal-title">Change password</h3><p>Set a new password for {selectedPasswordUser.name}.</p><form onSubmit={(event) => changePassword(event, selectedPasswordUser.id)}><Field label="New password" hint="At least 8 characters"><Input type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} placeholder="New password" minLength={8} autoComplete="new-password" required autoFocus /></Field><div className={styles.modalActions}><Button type="button" variant="ghost" onClick={() => { setPasswordUserId(undefined); setNewPassword(""); }}>Cancel</Button><Button disabled={passwordWorking}>{passwordWorking ? "Saving" : "Save password"}</Button></div></form></section></div>}</div>;
}
