package com.nirikshan.controller;
import com.nirikshan.dto.*;import com.nirikshan.dto.AuthRequests.*;import com.nirikshan.dto.AuthResponses.*;import com.nirikshan.model.*;import com.nirikshan.repository.*;import com.nirikshan.security.*;import jakarta.validation.Valid;import org.slf4j.*;import org.springframework.http.*;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/auth") public class AuthController {
 private static final Logger log=LoggerFactory.getLogger(AuthController.class);
 private final UserRepository users;private final PasswordEncoder passwords;private final JwtService jwt;private final CurrentUser current;
 public AuthController(UserRepository u,PasswordEncoder p,JwtService j,CurrentUser c){users=u;passwords=p;jwt=j;current=c;}
 @PostMapping("/signup") @ResponseStatus(HttpStatus.CREATED) public LoginResult signup(@Valid @RequestBody Signup r){String email=normalizeEmail(r.email());if(users.existsByEmailIgnoreCase(email))throw new IllegalArgumentException("An account already exists for this email");User u=new User();u.setName(r.name().trim());u.setEmail(email);u.setPasswordHash(passwords.encode(r.password()));u.setRole(UserRole.CITIZEN);users.save(u);return new LoginResult(jwt.create(u),info(u));}
 @PostMapping("/login") public LoginResult login(@Valid @RequestBody Login r){String email=normalizeEmail(r.email());User u=users.findByEmailIgnoreCase(email).orElse(null);if(u==null||!u.isActive()){log.warn("Login rejected for unknown or inactive account {}",email);throw new IllegalArgumentException("Invalid email or password");}if(!passwords.matches(r.password(),u.getPasswordHash())){log.warn("Login rejected because password verification failed for {}",email);throw new IllegalArgumentException("Invalid email or password");}log.info("Successful login for {} with role {}",email,u.getRole());return new LoginResult(jwt.create(u),info(u));}
 @GetMapping("/me") public UserInfo me(){return info(current.get());}
 @PostMapping("/change-password") public UserInfo change(@Valid @RequestBody ChangePassword r){User u=current.get();if(!passwords.matches(r.currentPassword(),u.getPasswordHash()))throw new IllegalArgumentException("Current password is incorrect");u.setPasswordHash(passwords.encode(r.newPassword()));u.setMustChangePassword(false);users.save(u);return info(u);}
 public static UserInfo info(User u){return new UserInfo(u.getId(),u.getEmail(),u.getName(),u.getRole(),u.isMustChangePassword(),u.getAssignedZone()==null?null:u.getAssignedZone().getId(),u.getAssignedZone()==null?null:u.getAssignedZone().getName(),u.getCreatedAt(),u.isActive());}
 private static String normalizeEmail(String email){return email.trim().toLowerCase(java.util.Locale.ROOT);}
}
