create table if not exists announcement_drafts (
    id bigint generated by default as identity primary key,
    zone_id bigint references zones(id),
    english_text varchar(2000) not null,
    hindi_text varchar(2000) not null,
    odia_text varchar(2000) not null,
    urgency varchar(32) not null,
    channel varchar(64) not null,
    source varchar(32) not null,
    approval_status varchar(64) not null,
    sent boolean not null default false,
    sent_at timestamp(6) with time zone,
    approved_by_user_id bigint references users(id),
    created_at timestamp(6) with time zone not null
);
create index if not exists idx_announcement_drafts_status on announcement_drafts(approval_status, sent);
