create table if not exists venues (
    id bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    description varchar(2000),
    latitude double precision,
    longitude double precision,
    name varchar(255) not null
);

create table if not exists zones (
    id bigint generated by default as identity primary key,
    current_density double precision not null,
    current_people_count integer not null,
    current_risk_level varchar(255) not null,
    last_updated timestamp(6) with time zone not null,
    latitude double precision,
    longitude double precision,
    name varchar(255) not null,
    polygon text,
    radius_meters double precision,
    venue_id bigint not null references venues(id)
);

create table if not exists users (
    id bigint generated by default as identity primary key,
    active boolean not null,
    created_at timestamp(6) with time zone not null,
    email varchar(255) not null unique,
    must_change_password boolean not null,
    name varchar(255) not null,
    password_hash varchar(255) not null,
    role varchar(255) not null,
    assigned_zone_id bigint references zones(id),
    created_by_admin_id bigint references users(id)
);

create table if not exists alerts (
    id bigint generated by default as identity primary key,
    message varchar(2000) not null,
    resolved boolean not null,
    resolved_at timestamp(6) with time zone,
    severity varchar(255) not null,
    "timestamp" timestamp(6) with time zone not null,
    zone_id bigint not null references zones(id)
);

create table if not exists citizen_reports (
    id bigint generated by default as identity primary key,
    description varchar(2000) not null,
    status varchar(255) not null,
    "timestamp" timestamp(6) with time zone not null,
    zone_id bigint not null references zones(id)
);

create table if not exists processing_jobs (
    id bigint generated by default as identity primary key,
    annotated_video_path varchar(255),
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    error_message text,
    status varchar(255) not null,
    summary_path varchar(255),
    video_filename varchar(255) not null,
    zone_id bigint not null references zones(id)
);

create table if not exists risk_events (
    id bigint generated by default as identity primary key,
    density_score double precision not null,
    explanation text not null,
    movement_speed double precision not null,
    people_count integer not null,
    risk_level varchar(255) not null,
    source_clip_id varchar(255),
    "timestamp" timestamp(6) with time zone not null,
    zone_id bigint not null references zones(id)
);

create table if not exists security_instructions (
    id bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    message varchar(2000) not null,
    created_by_id bigint not null references users(id),
    target_security_user_id bigint references users(id),
    target_zone_id bigint references zones(id)
);

create index if not exists idx_zones_venue_id on zones(venue_id);
create index if not exists idx_alerts_zone_id on alerts(zone_id);
create index if not exists idx_alerts_timestamp on alerts("timestamp");
create index if not exists idx_citizen_reports_zone_id on citizen_reports(zone_id);
create index if not exists idx_processing_jobs_zone_id on processing_jobs(zone_id);
create index if not exists idx_risk_events_zone_timestamp on risk_events(zone_id, "timestamp");
create index if not exists idx_security_instructions_zone_id on security_instructions(target_zone_id);
create index if not exists idx_security_instructions_user_id on security_instructions(target_security_user_id);
