alter table processing_jobs add column if not exists privacy_status varchar(64) not null default 'PENDING';
alter table zone_feeds add column if not exists privacy_status varchar(64) not null default 'PENDING';
create table if not exists privacy_audit_events (
    id bigint generated by default as identity primary key,
    action varchar(80) not null,
    resource_type varchar(80) not null,
    resource_id bigint,
    actor_user_id bigint,
    details varchar(500),
    created_at timestamp(6) with time zone not null
);
create index if not exists idx_privacy_audit_created_at on privacy_audit_events(created_at);
