create table if not exists zone_feeds (
    id bigint generated by default as identity primary key,
    zone_id bigint not null unique references zones(id),
    video_path varchar(1000) not null,
    video_filename varchar(255) not null,
    status varchar(255) not null,
    started_at timestamp(6) with time zone,
    current_loop_iteration integer not null default 0
);

create index if not exists idx_zone_feeds_status on zone_feeds(status);
