create table if not exists recommendations (
    id bigint generated by default as identity primary key,
    zone_id bigint references zones(id),
    type varchar(255) not null,
    message varchar(2000) not null,
    severity varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    status varchar(255) not null,
    acknowledged_by_user_id bigint references users(id)
);

create index if not exists idx_recommendations_status_created_at on recommendations(status, created_at desc);
create index if not exists idx_recommendations_zone_status on recommendations(zone_id, status);
